Added config scripts
hyphacoop/cosmos-organizing pull request #18
Opened 2021-09-30 16:07 UTC by ASoTNetworks

2021-10-06 15:00 UTC, uditvira commented
this looks good, but please continue on issue #19

2021-10-06 21:04 UTC, uditvira requested changes
left more comments

2021-10-06 21:04 UTC, uditvira commented on scripts/gaiad-config/config.toml
> +# min deposition amount
think you should have all of the following under a field called `[governance]` because these are all governance parameters

2021-10-06 21:04 UTC, uditvira commented on scripts/gaiad-config/config.toml
> +# validator power
these should come under validator.2

2021-10-08 16:59 UTC, ASoTNetworks commented
I have made some formatting changes to the toml config file is this how it should look?

2022-05-08 19:10 UTC, uditvira commented
This is a stale PR. Changes have moved to hyphacoop/cosmos-genesis-tinkerer

2022-05-08 19:10 UTC, closed without merging